name: GitHub Pages Deployment
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
          with:
            node-version: ">=15.9.0"
      - run: npm install
      - run: npm test
      - run: npm run deploy
